server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/{api_url}/**
        - id: ws_route
          uri: ws://localhost:8123
          predicates:
            - Path=/ws/{api_url}/**
    nacos:
      server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
#      filter:
#        enabled: false
  application:
    name: rain-api-gateway
#        - id: add_request_header_route
#          uri: http://localhost:8123
#          predicates:
#            - Path=/api/**
#          filters:
#            - AddRequestHeader=wz, aaa
#            - AddRequestParameter=name, blue
#            - name: CircuitBreaker
#              args:
#                name: fetchIngredients
#                fallbackUri: forward:/fallback
#        - id: fallback
#          uri: https://www.baidu.com
#          predicates:
#            - Path=/fallback

logging:
  level:
    org:
     springframework:
       cloud:
         gateway: trace
dubbo:
  application:
    name: dubbo
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848
#feign:
#  httpclient:
#    enabled: true # 支持HttpClient的开关
#    max-connections: 200 # 最大连接数
#    max-connections-per-route: 50 # 单个路径的最大连接数